name: Azure upload b2c Policies 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PowerShell
        run:  |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Process XML files
        run: pwsh ./process_xml.ps1 -environment ${{ github.event.inputs.environment }} -jsonConfigPath ./Config/parameters.json -inputFolder ./Policies

      - name: Upload processed XML files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-xml-files
          path: ./Config/${{ github.event.inputs.environment }}

      - name: 'Upload b2c Test Policy'
        uses: azure-ad-b2c/deploy-trustframework-policy@v3
        with:
          folder: "./Config/${{ github.event.inputs.environment }}"
          files: "b2ccluaitlab.onmicrosoft.com-B2C_1A_BASIC_A_BASE_MEDIASET_TEST_PUBLISH.xml"
          tenant: "${{ secrets.AZURE_TENANT_ID }}"
          clientId: "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret: "${{ secrets.AZURE_CLIENT_SECRET }}"
